name: Last Login
main: com.github.tommyjkk.lastlogin.LastLogin
version: 1
commands:
   lastlogin:
      description: This returns lastlogin of a player.
      usage: /<command> [player]
      permission: lastlogin.allow
      permission-message: You don't have <permission>
   totalplaytime:
      description: This returns the total playtime of a player in minutes.
      usage: /<command> [player]
      permission: totalplaytime.allow
      permission-message: You don't have <permission>